// <auto-generated />
namespace Meteo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class OpenWeatherCardContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OpenWeatherCardContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201511091602530_OpenWeatherCardContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
